version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
  build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t .
      - echo "Creating deployment package..."
      - zip -r deployment_package.zip . -x "*.git*" -x "*__pycache__*" -x "*.pyc"

artifacts:
  files:
    - deployment_package.zip