version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install -r requirements.txt -t .

  build:
    commands:
      - zip -r deployment_package.zip .

  post_build:
    commands:
      - aws lambda update-function-code \
          --function-name IntialFunction \
          --zip-file fileb://deployment_package.zip
